### ISSUE TITLE
Full Course Information Catalog Setup Issue

### ISSUE THREAD

**Issue by T4JI** [venkatesh-sivaraman/fireroad-server#33]
Hey, I'm an MIT student working on a personal project, and I'm having some issues setting up a catalog with all the course information (ratings, requirements, hours, etc. are all missing). I was wondering if you could just send a raw catalog text document that includes that information as well. Thanks in advance.

**Comment by venkatesh-sivaraman** [comment]
Hi, have you looked at the [FireRoad API](https://fireroad.mit.edu/reference)? The `/courses/all` endpoint offers a JSON of all courses, and the `/requirements` endpoints provide JSON versions of the major/minor requirements. Let us know if this is insufficient for your project and we'll see how else we can help.

**Comment by T4JI** [comment]
Thanks, exactly what I was looking for!
