### ISSUE TITLE
Fix schedule parsing for subjects in both IAP and Spring

### ISSUE THREAD

**Issue by cjquines** [venkatesh-sivaraman/fireroad-server#36]
compare https://fireroad.mit.edu/courses/lookup/18.02A and http://student.mit.edu/catalog/m18a.html#18.02A

**Comment by venkatesh-sivaraman** [comment]
Hi CJ, feel free to assign these issues to someone to put together a PR. I’m available to merge them once they’re verified to work on dev, or I can also give someone push access if that’s helpful :)
